NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

In [1]:
#import Numpy library
import numpy as np
ar=np.array([1,2,3,4,5,6])
print(ar)

[1 2 3 4 5 6]


In [2]:
#To check type
ar.dtype

dtype('int32')

In [3]:
#You can also change the type of the array
ar1=np.array([6,7,8,9,10], dtype='int16')
print(ar1)
print(ar1.dtype)

[ 6  7  8  9 10]
int16


In [4]:
a2d= np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(a2d)

[[1 2 3 4 5]
 [9 8 7 6 5]]


In [5]:
print(a2d.dtype)

int32


In [6]:
#Shape,dimensions,size,total size, no.of elements
print(f"To check the shape:{ar.shape} and 2d array: {a2d.shape}")
print(f"To check the dimension: {ar.ndim} and 2d array: {a2d.ndim}")
print(f"To check the size: {ar.size} and 2d array: {a2d.size}")# this will tell you the total element in the array
print(f"To check the Bytes: {ar.nbytes} and 2d array: {a2d.nbytes}")
print(f"To check the Item size: {ar.itemsize} and 2d array: {a2d.itemsize}")


To check the shape:(6,) and 2d array: (2, 5)
To check the dimension: 1 and 2d array: 2
To check the size: 6 and 2d array: 10
To check the Bytes: 24 and 2d array: 40
To check the Item size: 4 and 2d array: 4


In [7]:
# Manipulation of rows and columns
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
# Get a specific elemnts
print(a[0,3])
print(a[1,3])
print(a[1,5])
print(a[0,5])
print(a[1,2])
print(a[1,6])
print(a[0,0])

4
11
13
6
10
14
1


In [31]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
#Get a specific column
a[:,3]

array([ 4, 11])

In [39]:
a[0,1:-1:2] #Formula(start index:endindex:step)

array([2, 4, 6])

In [42]:
# Try to change the elemens
a[1,3]=32
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 32, 12, 13, 14]])

In [43]:
#3D example

a3d=np.array([[[1,2,3],[12,32,43],[65,54,34]]])
print(a3d)

[[[ 1  2  3]
  [12 32 43]
  [65 54 34]]]


In [48]:
# To get specif elemt from 3d array
a3d[0,2,1]

54

In [55]:
#Initialize different type of array
np.zeros((3,3), dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
np.ones((6,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [58]:
np.full((4,5),43)

array([[43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43]])

In [60]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [64]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
re=np.array([[1,2,3]])
r1=np.repeat(re,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [78]:
#copy the array
a=np.array([2,3,4,1,5])
cp=np.copy(a)
cp[1]=43
print(cp)
print(a)

[ 2 43  4  1  5]
[2 3 4 1 5]


In [84]:
#Math operations
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [85]:
a+2

array([3, 4, 5, 6])

In [86]:
a-2

array([-1,  0,  1,  2])

In [87]:
a*2

array([2, 4, 6, 8])

In [88]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [89]:
c=np.identity(2)
c

array([[1., 0.],
       [0., 1.]])

In [90]:
#Reshape
r1=np.arange(12).reshape(3,4)
print(r1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [91]:
r1.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [92]:
r1.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [93]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [94]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [95]:
print(np.diag([1,2,3,4]))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
a=np.array([2,3,4])
b=np.array([12,32,42])
a.a[1,3]=32
a.a[1,3]=32
a.(b)

In [ ]:
for i in ar:
    print(i)

In [ ]:
ar.ndim

In [ ]:
type(ar)

In [ ]:
ar.shape

In [ ]:
# Now we can also change the shape of this ar
ar.reshape(2,3)

In [ ]:
ar.reshape(3,2)

In [ ]:
arr2d=np.array(([1,2,3],[4,5,6]))
arr2d

In [ ]:
arr2d.ndim

In [ ]:
#Higher dimensions array
a5d=np.array([11,12,13,14,15,16],ndmin=5)
print(a5d)
print(a5d.ndim)

In [ ]:
a4d=np.array([132,31,43,31,431,31,3], ndmin=4)
print(a4d)
print(a4d.ndim)

In [ ]:
# Accessing the array list
ar[3]+ar[4]

In [ ]:
# Accesign the 2d element
t2d= np.array([[1,2,3,4,5], [6,7,8,9,19]])
print(t2d)
print(t2d[1,4])

In [ ]:
# Accesing the 3d element
t3d= np.array([[[1,2,3,4,5],[43,23,43,32,21],[5,2,6,7,8]]])
print(t3d)
print(t3d[0,0,2])

In [ ]:
import numpy as np
t4d=np.array([[[[1,2,3,4],[2,3,4,5],[6,7,8,9],[7,8,9,0]]]])
print(t4d)
print(type(t4d))
print(t4d.ndim)
print(t4d[0,0,0,3])

In [ ]:
t4d.reshape(2,8)

In [ ]:
t4d.reshape(8,2)

In [ ]:
t4d.transpose()

In [ ]:
op=np.array([1,2,3,4,5,3,4,5])
op.sum(axis=0)

In [ ]:
x=np.arange(27).reshape(9,3)
x

In [ ]:
#Axis 1 will work for row and 0 will work for columns
print(x.sum(axis=1))
print(x.sum(axis=0))
print(x.max())

In [ ]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
x[:1]

In [ ]:
#Linspace:Return evenly spaced numbers over a specified interval.
np.linspace(0,2,10)

In [ ]:
#zeros
z=np.zeros((4,5), dtype='int')
z

In [ ]:
#Ones
o=np.ones((2,5))
o

In [ ]:
#Random

np.random.random((4,4))

In [ ]:
#Empty
np.empty((2,2))

In [ ]:
#Astype: Convert to daratype
x.astype(type)

In [ ]:
#Append
a=np.array([7,6])
b=np.array([5,4])

print(np.append(a,b))

In [ ]:
np.insert(a,1,3)

In [ ]:
import numpy as np
a=np.array(([1,2,3,4],[5,6,4,3]))
a

In [ ]:
#Insert the element in one particular position
np.insert(a,1,25,axis=0)

In [ ]:
#Rezise the array
a.resize((4,2))

In [ ]:
a

In [1]:
#Delete operation in numpy
import numpy as np
d=np.arange(12).reshape(4,3)
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
d[0:3,1]

array([1, 4, 7])

In [29]:
d[1:2,:]

array([[3, 4, 5]])

In [30]:
l=[100,200,300]
a,b,c=l
print(b)

200


In [34]:
#To display the Month with dates
print(np.arange('2020-11','2020-12',dtype='datetime64[D]'))

['2020-11-01' '2020-11-02' '2020-11-03' '2020-11-04' '2020-11-05'
 '2020-11-06' '2020-11-07' '2020-11-08' '2020-11-09' '2020-11-10'
 '2020-11-11' '2020-11-12' '2020-11-13' '2020-11-14' '2020-11-15'
 '2020-11-16' '2020-11-17' '2020-11-18' '2020-11-19' '2020-11-20'
 '2020-11-21' '2020-11-22' '2020-11-23' '2020-11-24' '2020-11-25'
 '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29' '2020-11-30']


In [50]:
#to Display yesterday,today and tomorrow day print
import numpy as np
today=np.datetime64('today','D')
print("Today: ",today)
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print("Yesterday: ",yesterday)
Tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("Tomorrow: ",Tomorrow)

Today:  2020-12-13
Yesterday:  2020-12-12
Tomorrow:  2020-12-14


In [52]:
# count the number of days of a given month
print("No: Of days in March 2021: ")
print(np.datetime64("2021-04-01")-np.datetime64("2021-03-01"))

No: Of days in March 2021: 
31 days


In [43]:
#To find the first Monday in May 2017.
import numpy as np
print("First Monday in May 2017:")
print(np.busday_offset('2017-05', 0, roll='forward', weekmask='Mon'))


2020-12-12


In [56]:
print(np.busday_offset('2020-05',0,weekmask='Mon'))

ValueError: Non-business day date in busday_offset